package com.example.ui

enum class AppLanguage {
    ARABIC,
    ENGLISH
}

object Localization {
    private val ar = mapOf(
        "app_title" to "موغيم برو",
        "app_subtitle" to "كود ماستر هاب",
        "tagline" to "اطرح مهاراتك، تعلم، بع كود متميز ونمِّ شغفك البرمجي!",
        "nav_articles" to "المقالات التعليمية",
        "nav_store" to "متجر الأكواد",
        "nav_support" to "الدعم الفني والدردشة",
        "nav_admin" to "التحكم عن بعد (المالك)",
        "label_search" to "ابحث عن مقالات أو أكواد...",
        "label_language" to "English (EN)",
        "role_label" to "رتبة المستخدم الحالية:",
        "role_admin" to "مدير النظام (أدمن)",
        "role_developer" to "مطور مسجل (בائع)",
        "role_user" to "مستخدم عادي (مشتري)",
        "btn_switch_role" to "تغيير رتبة الحساب لعرض لوحة الإدارة",
        "price" to "السعر:",
        "download_size" to "الحجم:",
        "rating" to "التقييم:",
        "seller" to "البائع:",
        "buy_now" to "شراء وتنزيل الكود بأمان",
        "file_copied" to "تم نسخ الكود البرمجي بنجاح لمحافظتك وملفاتك المحلية!",
        "file_name" to "اسم الملف:",
        "empty_articles" to "لا يوجد مقالات تعليمية حالياً.",
        "empty_store" to "لا تتوفر برمجيات في المتجر حالياً.",
        "btn_add_article" to "إضافة دليل تعليمي جديد",
        "btn_add_product" to "طرح كود برامجي للبيع",
        "title_ar" to "العنوان بالوجيز العربي",
        "title_en" to "العنوان بالإنجليزية",
        "content_ar" to "المحتوى بالتفصيل العربي",
        "content_en" to "المحتوى بالإنجليزية",
        "category_ar" to "الفئة البرمجية بالعربية",
        "category_en" to "الفئة البرمجية بالإنجليزية",
        "price_val" to "سعر البيع بالدولار ($)",
        "code_content" to "الكود البرمجي (الصق الكود البرامجي الصالح هنا)",
        "filename" to "اسم الملف المقترح بالتنسيق الصحيح",
        "save" to "حفظ البيانات ونشرها فوراً",
        "cancel" to "إلغاء",
        "delete" to "حذف",
        "admin_only_section" to "قسم خاص بالمالك وأدمن النظام فقط",
        "analytics" to "تحليلات الأداء والإحصائيات عن بعد",
        "analytics_subtitle" to "تتبع حركة التدفق من دون ريستارت للتطبيق",
        "total_sales" to "إجمالي الإيرادات ($)",
        "total_downloads" to "إجمالي عدد الأكواد المبيعة",
        "popular_products" to "الأكواد الأكثر طلباً ومبيعاً:",
        "user_mgmt" to "إدارة الأعضاء والتحكم بالصلاحيات",
        "ticket_mgmt" to "الرد على استفسارات وتذاكر الدعم",
        "gateway_mgmt" to "التحكم في بوابات الدفع الإلكتروني",
        "add_gateway" to "إضافة قناة دفع برمجية",
        "gateway_name_ar" to "اسم البوابة بالعربية (مثال: فودافون كاش)",
        "gateway_name_en" to "اسم البوابة بالإنجليزية",
        "gateway_type" to "نوع البوابة (CREDIT_CARD , PAYPAL, WALLET)",
        "active" to "نشطة وقابلة للدفع",
        "inactive" to "معطلة مؤقتاً",
        "support_chat_desc" to "تواصل مباشرة ومباشرة مع فريق الدعم الفني لحل شيفرات الدفع أو مشاكل الأكواد.",
        "chat_placeholder" to "اكتب رسالة الدعم البرمجي هنا...",
        "send" to "إرسال",
        "buy_success" to "عملية شراء آمنة! تم دفع المبلغ وتحميل الكود البرمجي بنجاح.",
        "choose_pay" to "اختر وسيلة الدفع الآمنة المتطورة:",
        "close" to "إغلاق",
        "copied" to "تم النسخ!",
        "payment_methods_hint" to "يتم ربط وإعداد بوابات الدفع هذه عن بعد بصفتك أدمن التحكم.",
        "user_activity" to "سجل عمليات الشراء والنشاط الأخير:"
    )

    private val en = mapOf(
        "app_title" to "Mogame Pro",
        "app_subtitle" to "CodeMaster Hub",
        "tagline" to "Learn tutorials, buy & sell secure programming assets, and grow!",
        "nav_articles" to "Articles / Tutorials",
        "nav_store" to "Code Store",
        "nav_support" to "Direct Support Chat",
        "nav_admin" to "Remote Admin Module",
        "label_search" to "Search tutorials or snippets...",
        "label_language" to "العربية (AR)",
        "role_label" to "Active Identity Session:",
        "role_admin" to "Administrator (Owner)",
        "role_developer" to "Registered Dev (Seller)",
        "role_user" to "Standard Buyer (User)",
        "btn_switch_role" to "Simulate Developer / Admin Mode Toggle",
        "price" to "Price:",
        "download_size" to "Size:",
        "rating" to "Rating:",
        "seller" to "Seller:",
        "buy_now" to "Checkout & Download Code",
        "file_copied" to "Source code has been securely saved to clipboard & workspace!",
        "file_name" to "File Name:",
        "empty_articles" to "No programming tutorials listed yet.",
        "empty_store" to "No reusable snippet assets available for sale yet.",
        "btn_add_article" to "Publish Code Tutorial",
        "btn_add_product" to "List Code Snippet for Sale",
        "title_ar" to "Article Title (Arabic)",
        "title_en" to "Article Title (English)",
        "content_ar" to "Detailed Content (Arabic)",
        "content_en" to "Detailed Content (English)",
        "category_ar" to "Category (Arabic)",
        "category_en" to "Category (English)",
        "price_val" to "Listing Price in USD ($)",
        "code_content" to "Full Source Code Script (Enter clean, valid syntax)",
        "filename" to "Suggested code filename (e.g. login.py)",
        "save" to "Save & Remote Deploy",
        "cancel" to "Cancel",
        "delete" to "Delete",
        "admin_only_section" to "Administrator Panel (Remote Control Room)",
        "analytics" to "Remote Sales & Usage Analytics Dashboard",
        "analytics_subtitle" to "Track developer and customer actions instantly",
        "total_sales" to "Total Revenue ($)",
        "total_downloads" to "Source Code Downloads",
        "popular_products" to "Most popular purchased products:",
        "user_mgmt" to "Developer Registry & Roles Control",
        "ticket_mgmt" to "Direct Support Ticket Replies",
        "gateway_mgmt" to "Payment Gateways Config Dashboard",
        "add_gateway" to "Add Payment Gateway Option",
        "gateway_name_ar" to "Gateway Name (Arabic) (e.g., Vodafone Cash)",
        "gateway_name_en" to "Gateway Name (English)",
        "gateway_type" to "Gateway Type (CREDIT_CARD , PAYPAL, WALLET)",
        "active" to "Active & Operating",
        "inactive" to "Suspended Temporarily",
        "support_chat_desc" to "Communicate in real-time with the admin team to debug queries or receive transaction files.",
        "chat_placeholder" to "Type a secure developer ticket message...",
        "send" to "Send Message",
        "buy_success" to "Checkout Successful! Reusable script downloaded.",
        "choose_pay" to "Select Secure Pay Gateway:",
        "close" to "Close",
        "copied" to "Copied!",
        "payment_methods_hint" to "These options are hosted dynamically and configured by the administrator remotely.",
        "user_activity" to "Latest System Purchases & Logs:"
    )

    fun get(key: String, lang: AppLanguage): String {
        return if (lang == AppLanguage.ARABIC) {
            ar[key] ?: en[key] ?: key
        } else {
            en[key] ?: ar[key] ?: key
        }
    }
}
